- name: Check if instance directory exists
  stat:
    path: "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}"
  register: instance_dir

- name: Check if dbconfig.xml exists
  stat:
    path: "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}/dbconfig.xml"
  register: dbconfig_stat

- name: Check if eazybi.toml exists
  stat:
    path: "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}/eazybi.toml"
  register: eazybi_stat

- name: Check if server.xml exists
  stat:
    path: "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}/conf/server.xml"
  register: server_stat

- name: Check if setenv.sh exists
  stat:
    path: "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}/bin/setenv.sh"
  register: setenv_stat

- name: Check if jira-application.properties exists
  stat:
    path: "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}/atlassian-jira/WEB-INF/classes/jira-application.properties"
  register: jira_app_properties_stat

- name: Backup dbconfig.xml
  command: >
    cp -a "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}/dbconfig.xml"
          "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}_dbconfig.xml"
  become: true
  when: dbconfig_stat.stat.exists

- name: Backup eazybi.toml
  command: >
    cp -a "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}/eazybi.toml"
          "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}_eazybi.toml"
  become: true
  when: eazybi_stat.stat.exists


- name: Backup server.xml
  command: >
    cp -a "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}/conf/server.xml"
          "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}_server.xml"
  become: true
  when: server_stat.stat.exists

- name: Backup setenv.sh
  command: >
    cp -a "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}/bin/setenv.sh"
          "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}_setenv.sh"
  become: true
  when: setenv_stat.stat.exists

- name: Backup jira-application.properties
  command: >
    cp -a "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}/atlassian-jira/WEB-INF/classes/jira-application.properties"
          "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}_jira-application.properties.bak"
  become: true
  when: jira_app_properties_stat.stat.exists