- name: Set backup timestamp
  set_fact:
    backup_timestamp: "{{ ansible_date_time.iso8601 }}"

- name: Debug app
  debug:
    var: app

- name: Ensure backup directory exists
  file:
    path: "/tmp/{{ app }}_backup/{{ instance }}/{{ backup_timestamp }}"
    state: directory
    mode: '0755'

- name: Backup dbconfig.xml to controller
  ansible.builtin.command: >
    /bin/cp -a "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}/dbconfig.xml"
             "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}_dbconfig.xml"
  become: true

- name: Backup eazybi.toml to controller
  ansible.builtin.command: >
    /bin/cp -a "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}/eazybi.toml"
             "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}_eazybi.toml"
  become: true

- name: Backup server.xml to controller
  ansible.builtin.command: >
    /bin/cp -a "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}/conf/server.xml"
             "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}_server.xml"
  become: true

- name: Backup setenv.sh to controller
  ansible.builtin.command: >
    /bin/cp -a "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}/bin/setenv.sh"
             "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}_setenv.sh"
  become: true
