- name: Ensure instance directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}"
    - "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}"
  tags: [cleanup]

- name: Remove app and home directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}"
    - "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}"
  tags: [cleanup]
