---
- name: Archive and transfer app snapshots from production
  hosts: "{{ app }}"
  become: false
  gather_facts: true

  vars_files:
    - inventories/production/group_vars/vault.yml

  roles:
    - common

  pre_tasks:
    - name: Validate survey var
      ansible.builtin.assert:
        that:
          - app is defined
          - app in ['jira', 'confluence']

  tasks:

    - name: Create application snapshot
      import_role:
        name: snapshot_app
      tags: [snapshot]

    - name: Fetch archives to AWX controller
      import_role:
        name: fetch_archives
      tags: [fetch]
