---
- name: Archive and transfer app snapshots from production
  hosts: "{{ app }}"
  become: false
  gather_facts: false

  roles:
    - common

  tasks:

    - name: Create application snapshot
      import_role:
        name: snapshot_app
      when: app == "jira"
      tags: [snapshot]

    - name: Fetch archives to AWX controller
      import_role:
        name: fetch_archives
      tags: [fetch]
