---
- name: Archive and transfer app snapshots from production
  hosts: localhost
  become: true
  gather_facts: false

  roles:
    - common

  tasks:

    - name: Show inventory graph
      ansible.builtin.command:
        cmd: ansible-inventory --graph -i /runner/inventory/hosts
      register: inv

    - name: Dump groups
      ansible.builtin.debug:
        var: inv.stdout_lines

    - name: Create application snapshot
      import_role:
        name: snapshot_app
      when: app == "jira"
      tags: [snapshot]

    - name: Fetch archives to AWX controller
      import_role:
        name: fetch_archives
      tags: [fetch]
