---
# 1. Debug динамического инвентория AWX
- name: Debug AWX dynamic inventory
  hosts: localhost
  gather_facts: false
  become: false
  become_method: sudo
  become_flags: '-n'
  tasks:
    - name: Show inventory graph
      ansible.builtin.command:
        cmd: ansible-inventory --graph -i /runner/inventory/hosts
      register: inv_graph

    - name: Display group graph
      ansible.builtin.debug:
        var: inv_graph.stdout_lines

    - name: Dump inventory JSON
      ansible.builtin.command:
        cmd: ansible-inventory --list -i /runner/inventory/hosts
      register: inv_raw

    - name: Display raw inventory data
      ansible.builtin.debug:
        var: inv_raw.stdout_lines

# 2. Основной play: бэкап и сбор архивов
- name: Archive and transfer app snapshots from production
  hosts: "{{ app }}"
  become: true
  gather_facts: false

  roles:
    - common

  tasks:

    - name: Create application snapshot
      import_role:
        name: snapshot_app
      when: app == "jira"
      tags: [snapshot]

    - name: Fetch archives to AWX controller
      import_role:
        name: fetch_archives
      tags: [fetch]
