- name: Restore app to {{ env }} environment
  hosts: "{{ instance }}-{{ env }}"
  become: true
  become_user: "{{ ENV_USER }}"
  gather_facts: true

  vars:
    current_date: "{{ lookup('pipe', 'date +%Y%m%d') }}"

  vars_files:
    - "inventories/{{ env }}/group_vars/{{ instance }}/vault.yml"

  tasks:

    - name: Disable Jira plugins
      import_role:
        name: disable_plugins_jira
      when: app == "jira"
      tags: [disable_plugins]

    - name: Set banner
      import_role:
        name: set_banner
      tags: [set_banner]

    - name: Set Application Links
      import_role:
        name: set_application_links
      when: app == "jira"
      tags: [set_application_links]

    - name: Sync attachments
      import_role:
        name: sync_attachments
      when: INCLUDE_ATTACHMENTS | default(false) | bool
      tags: [sync_attachments]

    - name: Backup current config before deployment
      import_role:
        name: backup_config_test
      tags: [backup_test]