---
- name: Roll back to previous application snapshot on dev/int
  hosts: dev_int
  become: true
  gather_facts: false

  vars:
    rollback_snapshot_date: "{{ rollback_snapshot_date | default('') }}"

  pre_tasks:
    - name: Ensure rollback_snapshot_date is provided
      assert:
        that: rollback_snapshot_date | length > 0
        fail_msg: "❗ rollback_snapshot_date is required! Please specify it via extra-vars or prompt."

  roles:
    - common

  tasks:

    - name: Stop application service
      import_role:
        name: service_control
      tags: [stop]

    - name: Restore previous config backup
      import_role:
        name: backup_restore
      tags: [restore_config]

    - name: Remove failed deployment
      import_role:
        name: cleanup_app
      tags: [rollback_cleanup]

    - name: Re-deploy previous app/home from backup
      import_role:
        name: deploy_backup
      tags: [rollback_deploy]

    - name: Restore Jira DB from older dump
      import_role:
        name: db_restore_jira_backup
      when: app == "jira"
      tags: [rollback_db]

    - name: Restore Confluence DB from older dump
      import_role:
        name: db_restore_confluence_backup
      when: app == "confluence"
      tags: [rollback_db]

    - name: Start application service
      import_role:
        name: service_control
      tags: [start]
