---
- name: Ensure app_data instance dir exists
  file:
    path: "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}"
    state: directory
    mode: '0755'
  become: true

- name: Restore | dbconfig.xml <- parent
  ansible.builtin.command: >
    /bin/cp "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}_dbconfig.xml"
            "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}/dbconfig.xml"
  become: true

- name: Restore | eazybi.toml <- parent
  ansible.builtin.command: >
    /bin/cp "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}_eazybi.toml"
            "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}/eazybi.toml"
  become: true

- name: Ensure app_base instance dir exists
  file:
    path: "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}"
    state: directory
    mode: '0755'
  become: true

- name: Restore | server.xml <- parent
  ansible.builtin.command: >
    /bin/cp "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}_server.xml"
            "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}/conf/server.xml"
  become: true

- name: Restore | setenv.sh <- parent
  ansible.builtin.command: >
    /bin/cp "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}_setenv.sh"
            "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}/bin/setenv.sh"
  become: true

