---
- name: Create { app } app directory
  file:
    path: "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}"
    state: directory
    mode: '0755'

- name: Create {{ app }} home directory
  file:
    path: "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}"
    state: directory
    mode: '0755'

- name: Unpack app tarball
  unarchive:
    src: "{{ upload_dir }}/{{ now }}_{{ instance }}_appdata.tgz"
    dest: "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}"
    remote_src: yes

- name: Unpack home dir tarball
  unarchive:
    src: "{{ upload_dir }}/{{ now }}_{{ instance }}_homedir.tgz"
    dest: "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}"
    remote_src: yes
