---
- name: Restore | dbconfig.xml <- parent
  ansible.builtin.command: >
    /bin/cp "{{ app_data_base }}/{{ env }}/{{ app }}/jira/{{ instance }}_dbconfig.xml"
            "{{ app_data_base }}/{{ env }}/{{ app }}/jira/{{ instance }}/dbconfig.xml"
  become: true

- name: Restore | eazybi.toml <- parent
  ansible.builtin.command: >
    /bin/cp "{{ app_data_base }}/{{ env }}/{{ app }}/jira/{{ instance }}_eazybi.toml"
            "{{ app_data_base }}/{{ env }}/{{ app }}/jira/{{ instance }}/eazybi.toml"
  become: true

- name: Restore | server.xml <- parent
  ansible.builtin.command: >
    /bin/cp "{{ app_base }}/{{ env }}/{{ app }}/jira/{{ instance }}_server.xml"
            "{{ app_base }}/{{ env }}/{{ app }}/jira/{{ instance }}/conf/server.xml"
  become: true

- name: Restore | setenv.sh <- parent
  ansible.builtin.command: >
    /bin/cp "{{ app_base }}/{{ env }}/{{ app }}/jira/{{ instance }}_setenv.sh"
            "{{ app_base }}/{{ env }}/{{ app }}/jira/{{ instance }}/bin/setenv.sh"
  become: true

