- name: Set Jira backup paths
  set_fact:
    app_path: "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}"
    app_data_path: "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}"
    app_backup_path: "{{ app_base }}/{{ env }}/{{ app }}/{{ instance }}_backup"
    app_data_backup_path: "{{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }}_backup"

- name: Define Jira config files to backup
  set_fact:
    backup_files:
      - { src: "{{ app_data_path }}/dbconfig.xml", dest: "{{ app_data_backup_path }}/dbconfig.xml" }
      - { src: "{{ app_data_path }}/eazybi.toml", dest: "{{ app_data_backup_path }}/eazybi.toml" }
      - { src: "{{ app_path }}/conf/server.xml", dest: "{{ app_backup_path }}/server.xml" }
      - { src: "{{ app_path }}/bin/setenv.sh", dest: "{{ app_backup_path }}/setenv.sh" }
      - { src: "{{ app_path }}/atlassian-jira/WEB-INF/classes/jira-application.properties", dest: "{{ app_backup_path }}/jira-application.properties.bak" }
      - { src: "{{ app_data_path }}/secrets-config.yaml", dest: "{{ app_data_backup_path }}/secrets-config.yaml" }
      - { src: "{{ app_data_path }}/secured", dest: "{{ app_data_backup_path }}/secured" }
      - { src: "{{ app_data_path }}/keys", dest: "{{ app_data_backup_path }}/keys" }
  tags: [backup_jira]

- name: Ensure backup directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ app_data_backup_path }}"
    - "{{ app_backup_path }}"
  tags: [backup_jira]

- name: Check existence of config files/directories
  stat:
    path: "{{ item.src }}"
  loop: "{{ backup_files }}"
  register: file_stats
  tags: [backup_jira]

- name: Backup existing Jira config files/directories
  copy:
    src: "{{ item.item.src }}"
    dest: "{{ item.item.dest }}"
    remote_src: yes
    mode: preserve
  loop: "{{ file_stats.results | selectattr('stat.exists', 'equalto', true) | list }}"
  become: true
  tags: [backup_jira]
