---
- name: Set timestamp fact
  ansible.builtin.set_fact:
    now: "{{ lookup('pipe', 'date +%Y%m%d') }}"

- name: Ensure upload directory exists on target host
  file:
    path: "{{ upload_dir }}"
    state: directory
    mode: '0755'

- name: Copy DB dump (Jira only)
  ansible.builtin.copy:
    src: "{{ upload_dir }}/{{ source_instance_host }}/{{ now }}_{{ instance }}.dump"
    dest: "{{ upload_dir }}/"
    mode: '0644'
  when: app == "jira"

- name: Copy homedir archive
  ansible.builtin.copy:
    src: "{{ upload_dir }}/{{ source_instance_host }}/{{ now }}_{{ instance }}_homedir.tgz"
    dest: "{{ upload_dir }}/"
    mode: '0644'

- name: Copy appdata archive
  ansible.builtin.copy:
    src: "{{ upload_dir }}/{{ source_instance_host }}/{{ now }}_{{ instance }}_appdata.tgz"
    dest: "{{ upload_dir }}/"
    mode: '0644'
