---
- name: Push archives to dev/int host from AWX controller
  hosts: dev
    when: env = dev
  become: true
  gather_facts: false

  vars:
    now: "{{ lookup('pipe', 'date +%Y%m%d') }}"

  tasks:
    - name: Push app archive
      copy:
        src: "{{ upload_dir }}/{{ now }}_{{ instance }}_appdata.tgz"
        dest: "{{ upload_dir }}/"

    - name: Push home archive
      copy:
        src: "{{ upload_dir }}/{{ now }}_{{ instance }}_homedir.tgz"
        dest: "{{ upload_dir }}/"

    - name: Push DB dump (Jira only)
      copy:
        src: "{{ upload_dir }}/{{ now }}_{{ instance }}.dump"
        dest: "{{ upload_dir }}/"
      when: app == "jira"
