---
- name: Set timestamp (fallback if not provided)
  set_fact:
    now: "{{ now | default(ansible_date_time.iso8601_basic[:8]) }}"

- name: Ensure upload directory exists on target host
  ansible.builtin.file:
    path: "{{ upload_dir }}"
    state: directory
    mode: '0755'

- name: Check agent on INT
  shell: 'echo $SSH_AUTH_SOCK; ssh-add -L || true'
  delegate_to: "{{ inventory_hostname }}"
  become: true
  become_user: "{{ ENV_USER }}"
  changed_when: false

- name: Synchronize snapshot artifacts from AWX to target host
  ansible.posix.synchronize:
    src: "{{ ansible_user  }}@{{ hostvars[prod_instance_host].ansible_host }}:{{ snapshot_dir }}/"
    dest: "{{ upload_dir }}/"
    mode: pull
    archive: true
    compress: true
    use_ssh_args: true
    rsync_path: "sudo -n rsync"
    rsync_opts:
      - "--include={{ now }}_{{ instance }}.dump"
      - "--include={{ now }}_{{ instance }}_*.tgz"
      - "--exclude=*"
  delegate_to: "{{ inventory_hostname }}"
  become: true
  become_user: "{{ ENV_USER }}"
  # when: not ansible_check_mode
