---
- name: Set timestamp fact
  set_fact:
    now: "{{ lookup('pipe', 'date +%Y%m%d') }}"

- name: Ensure upload directory exists on target host
  ansible.builtin.file:
    path: "{{ upload_dir }}"
    state: directory
    mode: '0755'

- name: Synchronize snapshot artifacts from AWX to target host
  ansible.posix.synchronize:
    src: "{{ awx_upload_dir }}/{{ instance }}/"
    dest: "{{ upload_dir }}/"
    mode: push
    archive: true
    compress: true
    rsync_opts:
      - "--include={{ now }}_*.dump"
      - "--include={{ now }}_*.tgz"
      - "--exclude=*"
  delegate_to: localhost
  become: false
