- name: Create Confluence snapshot
  shell: >
    /usr/local/confluence/bin/create_snapshot.sh
    --dest "{{ upload_dir }}/confluence_{{ instance }}_{{ ansible_date_time.date }}.tgz"
  become_user: confluence

- name: Purge old snapshots
  find:
    paths: "{{ upload_dir }}"
    patterns: "confluence_{{ instance }}_*.tgz"
    age: "{{ snapshot_retention_days }}d"
    recurse: no
  register: old_conf_snapshots

- name: Delete old snapshots
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ old_conf_snapshots.files }}"
