- name: Set timestamp fact
  ansible.builtin.set_fact:
    now: "{{ ansible_date_time.date | regex_replace('-', '') }}"

- name: Ensure upload directory exists on AWX controller
  ansible.builtin.file:
    path: "{{ awx_upload_dir }}/{{ inventory_hostname }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  run_once: true
  become: false

- name: Synchronize only current day's snapshot files
  ansible.posix.synchronize:
    src: "{{ snapshot_dir }}/"
    dest: "{{ awx_upload_dir }}/{{ inventory_hostname }}/"
    mode: pull
    archive: true
    compress: true
    rsync_opts:
      - "--include={{ now }}_*.dump"
      - "--include={{ now }}_*.tgz"
      - "--exclude=*"
  delegate_to: localhost
  become: false

