---
- name: Restore PostgreSQL DB using Ansible module
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    state: restore
    target: "{{ upload_dir }}/{{ now }}_{{ instance }}.dump"
    login_host: "{{ db_host }}"
    login_port: "{{ db_port | default(5432) }}"
    login_user: "{{ db_user }}"
    login_password: >-
      {{ (app == 'jira') | ternary(jira_db_password, confluence_db_password) }}
    encoding: UTF8
    target_opts: "-c --if-exists"
  register: restore_result
  become: false
  tags: restore
