---
- name: Ensure snapshot directory exists
  file:
    path: "{{ snapshot_dir }}"
    state: directory
    mode: '0755'

- name: Create PostgreSQL DB dump (Jira only)
  shell: >
    pg_dump -h {{ db_host }} -U {{ db_user }} -Fc {{ db_name }}
    > {{ snapshot_dir }}/{{ now }}_{{ instance }}.dump
  become_user: postgres
  when: app == "jira"

- name: Create filtered homedir archive
  shell: >
    tar --exclude='caches' --exclude='logs' --exclude='tmp' -zcf
    {{ snapshot_dir }}/{{ now }}_{{ instance }}_homedir.tgz
    -C {{ app_data_base }}/{{ env }}/{{ app }}/{{ instance }} .
  become: true

- name: Create filtered app archive
  shell: >
    tar -zcf {{ snapshot_dir }}/{{ now }}_{{ instance }}_appdata.tgz
    -C {{ app_base }}/{{ env }}/{{ app }}/{{ instance }} .
  become: true

- name: Clean old snapshot files
  find:
    paths: "{{ snapshot_dir }}"
    patterns: "{{ instance }}_*"
    age: "{{ snapshot_retention_days | default(7) }}d"
    recurse: no
  register: old_snapshots

- name: Delete old snapshot files
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ old_snapshots.files }}"
