---
- name: Restore PostgreSQL DB from dump (app-user only, no sudo)
  shell: |
    export PGPASSWORD="{{ (app == 'jira') 
                          | ternary(jira_envword, confluence_envword) }}" \
    pg_restore -U {{ db_user }} -h {{ db_host }} -p {{ db_port | default(5432) }} \
      -c --if-exists -d {{ db_name }} {{ upload_dir }}/{{ now }}_{{ instance }}.dump
  args:
    executable: /bin/bash
  register: restore_result
  changed_when: "'restoring data' in restore_result.stdout or 'processing data' in restore_result.stdout"
  failed_when: restore_result.rc != 0
  tags: restore

