- name: Ensure snapshot directory exists
  file:
    path: "{{ snapshot_dir }}"
    state: directory
    mode: '0755'

- name: Set timestamp fact
  set_fact:
    now: "{{ ansible_date_time.date | regex_replace('-', '') }}"

- name: Dump PostgreSQL DB using pg_dump
  shell: |
    export PGPASSWORD="{{ db_pass }}" && \
    pg_dump -U {{ db_user }} -h {{ db_host }} -p {{ db_port | default(5432) }} \
      -Fc {{ db_name }} > {{ snapshot_dir }}/{{ now }}_{{ instance }}.dump
  args:
    executable: /bin/bash

- name: Find first-level attachment subdirs (excluding 'insight')
  find:
    paths: "{{ application_data_home }}/data/attachments"
    file_type: directory
    recurse: no
    patterns: '*'
    excludes: insight
  register: attachment_dirs
  ignore_errors: true

- name: Render exclude-from file
  template:
    src: excl_attachments.txt.j2
    dest: "{{ snapshot_dir }}/excl_attachments.txt"
  when: attachment_dirs.files | length > 1

- name: Create homedir archive
  shell: |
    tar \
      --exclude='./caches/*' \
      --exclude='./data/backbone-issue-sync/*' \
      --exclude='./data/git-plugin/*' \
      --exclude='./eazybi.toml' \
      --exclude='./export/*' \
      --exclude='./import/*' \
      --exclude='./log/*' \
      --exclude='./tmp/*' \
      {% if attachment_dirs.files|length > 1 %}
      --exclude-from='{{ snapshot_dir }}/excl_attachments.txt' \
      {% endif %}
      -zcvf '{{ snapshot_dir }}/{{ now }}_{{ instance }}_homedir.tgz' .
  args:
    chdir: "{{ application_data_home }}"
  become: true

- name: Remove temporary exclude-from file
  file:
    path: "{{ snapshot_dir }}/excl_attachments.txt"
    state: absent
  when: attachment_dirs.files | length > 1

- name: Set permissions on attachment dirs
  file:
    path: "{{ item.path }}"
    mode: '0750'
  loop: "{{ lookup('ansible.builtin.find', paths=application_data_home + '/data/attachments', file_type='directory', recurse=True).files }}"
  when: lookup('ansible.builtin.stat', application_data_home + '/data/attachments').stat.exists
  become: true

- name: Set permissions on attachment files
  file:
    path: "{{ item.path }}"
    mode: '0640'
  loop: "{{ lookup('ansible.builtin.find', paths=application_data_home + '/data/attachments', file_type='file', recurse=True).files }}"
  when: lookup('ansible.builtin.stat', application_data_home + '/data/attachments').stat.exists
  become: true

- name: Create appdata archive
  shell: |
    tar \
      --exclude='./temp/*' \
      --exclude='./logs/*' \
      --exclude='./work/*' \
      -zcvf '{{ snapshot_dir }}/{{ now }}_{{ instance }}_appdata.tgz' .
  args:
    chdir: "{{ application_install_dir }}"
  become: true

- name: Find old snapshots
  find:
    paths: "{{ snapshot_dir }}"
    patterns: "{{ instance }}_*"
    age: "{{ snapshot_retention_days }}d"
    recurse: no
  register: old_snapshots

- name: Remove old snapshots
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ old_snapshots.files }}"
  when: old_snapshots.matched > 0
