all:
  children:
    int:
      children:
        jira:
          hosts:
            pilot-aftersales-int:
              ansible_host: sndca00578i.polygran.noris.de
            mercedes-shared-jira-int:
              ansible_host: sndca00578i.polygran.noris.de
            daimler-shared-jira-int:
              ansible_host: sndca00645i.polygran.noris.de
        confluence:
          hosts:
            pilot-aftersales-confluence-int:
              ansible_host: sndca00578i.polygran.noris.de
            shared-jira-confluence-int:
              ansible_host: sndca00578i.polygran.noris.de
    dev:
      children:
        jira:
          hosts:
            pilot-aftersales-dev:
              ansible_host: sndca00578i.polygran.noris.de
            mercedes-shared-jira-dev:
              ansible_host: sndca00578i.polygran.noris.de
            daimler-shared-jira-dev:
              ansible_host: sndca00645i.polygran.noris.de
        confluence:
          hosts:
            pilot-aftersales-confluence-dev:
              ansible_host: sndca00578i.polygran.noris.de
            mercedes-shared-jira-confluence-dev:
              ansible_host: sndca00578i.polygran.noris.de
            daimler-shared-jira-confluence-dev:
              ansible_host: sndca00645i.polygran.noris.de
    prod:
      children:
        jira:
          hosts:
            pilot-aftersales:
              ansible_host: sndca00572p.polygran.noris.de
            mercedes-shared-jira:
              ansible_host: sndca00558p.polygran.noris.de
            daimler-shared-jira:
              ansible_host: sndca00643p.polygran.noris.de
        confluence:
          hosts:
            pilot-aftersales-confluence:
              ansible_host: sndca00573p.polygran.noris.de
            mercedes-shared-confluence:
              ansible_host: sndca00559p.polygran.noris.de
            daimler-shared-confluence:
              ansible_host: sndca00643p.polygran.noris.de
