all:
  children:
    int:
      children:
        jira:
          hosts:
            pilot-aftersales-int:
              ansible_host: sndca00578i.polygran.noris.de
        confluence:
          hosts:
            pilot-aftersales-confluence-int:
              ansible_host: sndca00578i.polygran.noris.de
    dev:
      children:
        jira:
          hosts:
            pilot-aftersales-dev:
              ansible_host: sndca00578i.polygran.noris.de
        confluence:
          hosts:
            pilot-aftersales-confluence-dev:
              ansible_host: sndca00578i.polygran.noris.de
    prod:
      children:
        jira:
          hosts:
            pilot-aftersales:
                  ansible_host: sndca00572p.polygran.noris.de
        confluence:
          hosts:
            pilot-aftersales-confluence:
                  ansible_host: sndca00573p.polygran.noris.de
