all:
  children:
    int:
      hosts:
        atlassian-int.mercedes-benz.polygran.de:
          ansible_host: sndca00578i.polygran.noris.de
    dev:
      hosts:
        atlassian-dev.mercedes-benz.polygran.de:
          ansible_host: sndca00578d.polygran.noris.de
