all:
  children:
    int:
      hosts:
        pilot-aftersales-int.mercedes-benz.polygran.de:
          ansible_host: sndca00578i.polygran.noris.de
        pilot-aftersales-confluence-int.mercedes-benz.polygran.de:
          ansible_host: sndca00578i.polygran.noris.de
    dev:
      hosts:
        pilot-aftersales-confluence-dev.mercedes-benz.polygran.de:
          ansible_host: sndca00578d.polygran.noris.de
    prod:
      hosts:
        pilot-aftersales.mercedes-benz.polygran.de:
          ansible_host: sndca00572p.polygran.noris.de
        pilot-aftersales-confluence.mercedes-benz.polygran.de:
          ansible_host: sndca00573p.polygran.noris.de
