---
# - name: Set service name depending on environment
#   set_fact:
#     SERVICE_NAME: "{{ lookup('vars', env | upper + '_SERVICE_NAME') }}"

- name: Stop service
  ansible.builtin.service:
    name: "{{ SERVICE_NAME }}"
    state: stopped
  when:
    - service_action == "stop"
    - app == "jira"
  register: stop_result
  ignore_errors: false
  become: true
  become_user: "{{ ansible_user }}"
  tags: [service_control]

- name: Start service
  ansible.builtin.service:
    name: "{{ SERVICE_NAME }}"
    state: started
  when:
    - service_action == "start"
    - app == "jira"
  register: start_result
  ignore_errors: false
  become: true
  become_user: "{{ ansible_user }}"
  tags: [service_control]
