---
- name: Stop service
  ansible.builtin.service:
    name: "{{ SERVICE_NAME }}"
    state: stopped
  become: true
  tags: stop

- name: Start service
  ansible.builtin.service:
    name: "{{ SERVICE_NAME }}"
    state: started
  become: true
  tags: start
