---
- name: Set service name depending on environment
  set_fact:
    SERVICE_NAME: "{{ lookup('vars', env | upper + '_SERVICE_NAME') }}"

- name: Stop service
  ansible.builtin.service:
    name: "{{ SERVICE_NAME }}"
    state: stopped
  when:
    - service_action == "stop"
    - "'int' in group_names"

- name: Start service
  ansible.builtin.service:
    name: "{{ SERVICE_NAME }}"
    state: started
  when:
    - service_action == "start"
    - "'int' in group_names"
