---
- name: Ensure snapshot and restore directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - "{{ upload_dir }}"
    - "{{ snapshot_dir }}"

# - name: Install required system packages
  package:
    name:
      - tar
      - rsync
      - postgresql-client
      - python3-psycopg2
    state: present
  become: true