all:
  children:
    production:
      children:
        jira:
          hosts:
            pilot-aftersales.mercedes-benz.polygran.de:
              ansible_host: sndca00572p.polygran.noris.de
            shared-jira.mercedes-benz.polygran.de:
              ansible_host: sndca00558p.polygran.noris.de

        confluence:
          hosts:
            pilot-aftersales-confluence.mercedes-benz.polygran.de:
              ansible_host: sndca00573p.polygran.noris.de
            shared-confluence.mercedes-benz.polygran.de:
              ansible_host: sndca00559p.polygran.noris.de