---
- hosts: all
  gather_facts: false
  vars_prompt:
    - name: instance
      prompt: "Type name of instance (exemple, mbb-jira или online-help)"
      private: no

  roles:
    - role: update_env
