---
- name: Check if important config files and directories exist
  stat:
    path: "{{ item.path }}"
  register: file_check
  loop:
    - { name: "dbconfig", path: "{{ jira_data_base }}/dbconfig.xml" }
    - { name: "eazybi", path: "{{ jira_data_base }}/eazybi.toml" }
    - { name: "server", path: "{{ jira_base }}/conf/server.xml" }
    - { name: "setenv", path: "{{ jira_base }}/bin/setenv.sh" }
    - { name: "jira_properties", path: "{{ jira_base }}/atlassian-jira/WEB-INF/classes/jira-application.properties" }
    - { name: "secrets", path: "{{ jira_data_base }}/secrets-config.yaml" }
    - { name: "secured_dir", path: "{{ jira_data_base }}/secured" }
    - { name: "keys_dir", path: "{{ jira_data_base }}/keys" }
  tags: [backup_jira]

- name: Ensure backup directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ jira_data_backup_root }}"
    - "{{ jira_backup_root }}"
  tags: [backup_jira]

- name: Backup Jira configuration and directories to {{ instance }}_backup
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
    mode: preserve
  loop:
    - { src: "{{ jira_data_base }}/dbconfig.xml", dest: "{{ jira_data_backup_root }}/dbconfig.xml" }
    - { src: "{{ jira_data_base }}/eazybi.toml", dest: "{{ jira_data_backup_root }}/eazybi.toml" }
    - { src: "{{ jira_base }}/conf/server.xml", dest: "{{ jira_backup_root }}/server.xml" }
    - { src: "{{ jira_base }}/bin/setenv.sh", dest: "{{ jira_backup_root }}/setenv.sh" }
    - { src: "{{ jira_base }}/atlassian-jira/WEB-INF/classes/jira-application.properties", dest: "{{ jira_backup_root }}/jira-application.properties.bak" }
    - { src: "{{ jira_data_base }}/secrets-config.yaml", dest: "{{ jira_data_backup_root }}/secrets-config.yaml" }
    - { src: "{{ jira_data_base }}/secured/", dest: "{{ jira_data_backup_root }}/secured/" }
    - { src: "{{ jira_data_base }}/keys/", dest: "{{ jira_data_backup_root }}/keys/" }
  become: true
  tags: [backup_jira]

