---
- name: Backup configs
  include_tasks: backup_config.yml
  tags: backup

- name: Remove existing app
  include_tasks: wipe_app.yml
  tags: wipe

- name: Unpack tarballs
  include_tasks: unpack_app.yml
  tags: unpack

- name: Restore PostgreSQL DB
  include_tasks: restore_db.yml
  tags: db

- name: Apply SQL patches and branding
  include_tasks: patch_sql.yml
  tags: patch

- name: Cleanup temporary files
  include_tasks: finalize.yml
  tags: cleanup
